### ISSUE TITLE
vidyo-electron Rendering level and crash

### ISSUE THREAD

**Issue by FreeLiC** [Vidyo/vidyo.io-connector-electron#5]
First: About vidyo's rendering level, because I want to customize some of the content in vidyo rendered video, but vidyo's rendering level seems very high, so my CSS style can't cover the video rendered in vidyo, this is me The more important issues currently encountered.
Second: It is about the crash on the vidyo electron version. The screenshot of the crash is as follows:
51:39.565 +00:00: ERROR: VidyoClient: Execute Async-0: c:\cygwin64\tmp\sdk.release.trinity_19_2_1_9.build.mreyufwsyc\source\sdk\lmi\vidyoclient\vidyoendpoint.c:773: CrashHandler_: CrashHandler:
  c:\cygwin64\tmp\sdk.release.trinity_19_2_1_9.build.mreyufwsyc\source\sdk\lmi\utils\lmicrashhandler.c (82): LmiCrashHandlerCalled+8
  UnhandledExc
┗ ----------------------------

┏ Electron -------------------

  eptionFilter+416
  RtlCaptureStackContext+124193
  RtlAreBitsSet+88

**Comment by tmelko-vidyo** [comment]
This issue has been reported via customer support and duplicated here. Let's proceed with the discussion within the opened case. Closing this thread.

**Comment by walokra** [comment]
What was the answer to that first question?

**Comment by tmelko-vidyo** [comment]
> What was the answer to that first question?

It's true, any CSS would be ignored because rendering div is not actually located in your window since it is a child-window (or sub-view on mac) of the parent electron browser window. It's not like a regular hierarchy and it's always placed on top so moreover, you can't place any UI elements over. Even z-index won't help in this case.

Currently, it's listed as a limitation of electron plus VidyoAddon solution.
